name: Renovate

on:
  schedule:
    - cron: '0/15 * * * *' # every 15 minutes
  push:
    branches:
      - 'gha/renovate' # for debugging this workflow
  workflow_dispatch: # also for debugging

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Get token
        id: get_token
        uses: actions/create-github-app-token@29824e69f54612133e76f7eaac726eef6c875baf # v2
        with:
          app-id: ${{ secrets.RENOVATE_APP_ID }}
          private-key: ${{ secrets.RENOVATE_APP_KEY }}

      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@822441559e94f98b67b82d97ab89fe3003b0a247 # v44.2.0
        with:
          token: '${{ steps.get_token.outputs.token }}'
        env:
          RENOVATE_PLATFORM_COMMIT: 'true'
          RENOVATE_AUTODISCOVER: 'true'
